// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroRole", b =>
                {
                    b.Property<int>("HeroesId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("HeroesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("HeroRole");

                    b.HasData(
                        new
                        {
                            HeroesId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            HeroesId = 2,
                            RolesId = 2
                        },
                        new
                        {
                            HeroesId = 3,
                            RolesId = 3
                        },
                        new
                        {
                            HeroesId = 4,
                            RolesId = 4
                        },
                        new
                        {
                            HeroesId = 5,
                            RolesId = 5
                        },
                        new
                        {
                            HeroesId = 6,
                            RolesId = 3
                        },
                        new
                        {
                            HeroesId = 6,
                            RolesId = 5
                        });
                });

            modelBuilder.Entity("WebApi.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mysterious creature that can split into many smaller ones.",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage_1_9_642/100_8b401d50920f2359060a9c7a3c833df1.png",
                            Name = "Gloo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A legendary Sacred Beast that can take the form of a ranbunctious young man.",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage_1_9_20/100_454c13b2de7b7d1a20fbf553c620510d.png",
                            Name = "Lukas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A scholar that wanders the universe with split souls to save his daughter.",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage/100_0495066df0d828c149e7fe89aa63078b.png",
                            Name = "Nolan"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A mysterious young woman who guides the ember butterflies using her Lantern ...",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage_92/100_13cfeec4bec7a27a09677e519f1ef9d2.png",
                            Name = "Zhuxin"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Leader of the Scarlet Sect, in the Scarlet Shadow of the Cadia Riverlands.",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage/100_85d213390613bbc09220cf1d9f64c5c0.png",
                            Name = "Hanabi"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Adopted daughter of House Vance, a clandestine sniper.",
                            ImageUrl = "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/homepage/100_f4f42410c90f84e4d46b129d5e8887e8.png",
                            Name = "Lesley"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeroRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryFunction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeroRole = "Tank",
                            KeyAttributes = "High health, defense, and crowd control.",
                            LogoUrl = "https://static.wikia.nocookie.net/mobile-legends/images/f/f0/Tank_Icon.png",
                            PrimaryFunction = "Protect teammates, soak damage, and initiate team fights."
                        },
                        new
                        {
                            Id = 2,
                            HeroRole = "Fighter",
                            KeyAttributes = "Balanced stats, good damage output, and decent survivability.",
                            LogoUrl = "https://static.wikia.nocookie.net/mobile-legends/images/1/1a/Fighter_Icon.png",
                            PrimaryFunction = "Balance damage and durability, capable of engaging in fights and soaking damage."
                        },
                        new
                        {
                            Id = 3,
                            HeroRole = "Assassin",
                            KeyAttributes = "High burst damage, mobility, and stealth.",
                            LogoUrl = "https://static.wikia.nocookie.net/mobile-legends/images/3/3f/Assassin_Icon.png",
                            PrimaryFunction = "Quickly eliminate enemy heroes in team fights."
                        },
                        new
                        {
                            Id = 4,
                            HeroRole = "Mage",
                            KeyAttributes = "High magic power, magical damage, and often crowd control.",
                            LogoUrl = "https://static.wikia.nocookie.net/mobile-legends/images/5/53/Mage_Icon.png",
                            PrimaryFunction = "Deal high magic damage, often with range and crowd control."
                        },
                        new
                        {
                            Id = 5,
                            HeroRole = "Marksman",
                            KeyAttributes = "High attack speed, physical damage, and ranged attack.",
                            LogoUrl = "https://static.wikia.nocookie.net/mobile-legends/images/1/10/Marksman_Icon.png",
                            PrimaryFunction = "Deal high physical damage, primarily from a distance."
                        });
                });

            modelBuilder.Entity("HeroRole", b =>
                {
                    b.HasOne("WebApi.Models.Hero", null)
                        .WithMany()
                        .HasForeignKey("HeroesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
